modLoader="javafml"
loaderVersion="[47,)"
license="EUPL-1.2"
[[mods]]
modId="terrafirmascout"
version="${file.jarVersion}"
displayName="TerraFirmaScout"
description='''Find a TFC seed that suits your play style, or build a wishlist for your next world.'''
[[mixins]]
config="terrafirmascout.mixins.json"
[[dependencies.terrafirmascout]]
modId="forge"
mandatory=true
versionRange="[47.2.20,)"
ordering="NONE"
side="BOTH"
[[dependencies.terrafirmascout]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.terrafirmascout]]
modId="tfc"
mandatory=true
versionRange="[3.2.25,3.3)"
ordering="AFTER"
side="BOTH"
