modLoader="javafml"
loaderVersion="[4,)"
license="EUPL-1.2"
issueTrackerURL="https://github.com/DelusionalWizard/TFC-Scout/issues"
[[mods]]
modId="terrafirmascout"
version="1.0.1"
displayName="TerraFirmaScout"
authors="Cooper"
displayURL="https://github.com/DelusionalWizard/TFC-Scout"
description='''Find a TFC seed that suits your play style, or build a wishlist for your next world.'''
[[mixins]]
config="terrafirmascout.mixins.json"
[[dependencies.terrafirmascout]]
modId="neoforge"
type="required"
versionRange="[21.1.234,)"
ordering="NONE"
side="BOTH"
[[dependencies.terrafirmascout]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[dependencies.terrafirmascout]]
modId="tfc"
type="required"
versionRange="[4.2.11]"
ordering="AFTER"
side="BOTH"
